### ISSUE TITLE
CS-CORE in the combination with zero imputation 

### ISSUE THREAD

**Issue by kogamin** [ChangSuBiostats/CS-CORE#2]
Hi there, I wanted to get your opinion on running CS-CORE using a zero-imputed matrix (e.g., CS-CORE in combination with ALRA, MAGIC, or scImpute). Would it work fine, or could there be any theoretical issues?

**Comment by ChangSuBiostats** [comment]
Hi,

Thanks for your question. I will suggest against doing so, as imputation tends to introduce spurious correlations between genes, as demonstrated in this paper: https://www.sciencedirect.com/science/article/pii/S2666389921000210

Best,
Chang


From: kogamin ***@***.***>
Date: Friday, August 9, 2024 at 5:30 AM
To: ChangSuBiostats/CS-CORE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [ChangSuBiostats/CS-CORE] CS-CORE in the combination with zero imputation (Issue #2)

Hi there, I wanted to get your opinion on running CS-CORE using a zero-imputed matrix (e.g., CS-CORE in combination with ALRA, MAGIC, or scImpute). Would it work fine, or could there be any theoretical issues?

**Comment by kogamin** [comment]
Thank you for your answer. I will use raw matrix as an input.
